### PR TITLE
Bug bash application pods resource changes for ngsa and loderunner

### PR DESCRIPTION
**Pull request by AAkindele**
# Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

- updated resource and request limits for ngsa and loderunner deployments
- added istio blocks to the ngsa deployments so that istio auto injection can merge resource updates to injected container
- made changes to all cluster directories
- updated the matching template files in the template directory

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [ ] Unit tests updated and ran successfully
- [ ] Update documentation or issue referenced above

## Issues Closed or Referenced

- Closes https://github.com/retaildevcrews/wcnp/issues/1014
- References https://github.com/retaildevcrews/wcnp/issues/1001

### CODE REVIEW

**Review by joaquinrz — CHANGES_REQUESTED** [review]
The loderunner, ngsa-app, and ngsa-java files will be overriden by autogitops. These changes must be done in the app repos under autpgitops folder. Feel free to msg me or @alfredoihernandez if running into any issues

**Comment by kforeverisback** [comment]
> The loderunner, ngsa-app, and ngsa-java files will be overriden by autogitops. These changes must be done in the app repos under autpgitops folder. Feel free to msg me or @alfredoihernandez if running into any issues

Can't believe we forgot about AGO. We'll make a PR in the respective app repos

**Comment by kforeverisback** [comment]
@joaquinrz @alfredoihernandez
App specific PRs:
NGSA: https://github.com/retaildevcrews/ngsa-app/pull/129
LodeRunner: https://github.com/retaildevcrews/loderunner/pull/304

Will close this PR once both of them are merged

**Comment by joaquinrz** [comment]
@kforeverisback I think we should keep the changes in the templates/ folder

**Comment by kforeverisback** [comment]
@joaquinrz We're removed all sidecar cofig from here.
Left template and some comments on ngsa-cosmos on how to add istio-proxy container block

**Review by joaquinrz — APPROVED** [review]

**Pull request merged**
