### PR TITLE
Deploy automation runbook dashboard and burst service to all clusters.

### PR DESCRIPTION
**Pull request by AAkindele**
# Type of PR

- [x] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

Fix Grafana deployment bug by deploying the missing Automation Runbook dashboard configmap to all clusters. Currently, the Grafana deployments in most of the clusters are referencing the missing configmap. The dashboard flux substitution kustomization moved from dev east folder to base folder. The setup is also simplified by adding a reference to the dashboard flux substitution kustomization in the same place where all the other dashboards are referenced.

Deploy burst service to all the clusters.

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [ ] Unit tests updated and ran successfully
- [x] Update documentation or issue referenced above

## Issues Closed or Referenced

- Closes https://github.com/retaildevcrews/wcnp/issues/1219
- Closes https://github.com/retaildevcrews/wcnp/issues/1218

### CODE REVIEW

**Review by kforeverisback — APPROVED** [review]
LGTM
⚡ 💥

**Review by gortegaMS — APPROVED** [review]
LGTM

**Comment by kforeverisback** [comment]
@AAkindele Quick query: burst metrics were only deployed in WestUS2 before, are we planning to use Burst Metrics for all of our clusters?

**Comment by AAkindele** [comment]
> @AAkindele Quick query: burst metrics were only deployed in WestUS2 before, are we planning to use Burst Metrics for all of our clusters?

I believe the goal is to simplify by adding it to all clusters. That way, folks won't have to remember which cluster it was deployed to. @pragmatical can chime in with more details here in case I'm missing anything.

**Pull request merged**
